services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: postpass
      POSTGRES_DB: empstat
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
